# Generated by Django 4.1.1 on 2022-10-12 05:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0012_alter_photo_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAnuncio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaConvenio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostEquipHosp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/equip/')),
                ('quantidade', models.PositiveSmallIntegerField(help_text='Quantidade disponível')),
                ('disponibilidade', models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Indisponível')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PostEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('corpo', ckeditor_uploader.fields.RichTextUploadingField()),
                ('galeria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.gallery')),
                ('imagem_previa', models.ForeignKey(blank=True, help_text='Imagem prévia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.photo')),
            ],
        ),
        migrations.CreateModel(
            name='PostConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('contato', models.TextField(max_length=100)),
                ('texto_convenio', ckeditor_uploader.fields.RichTextUploadingField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriaconvenio', verbose_name='Categoria do Anúncio')),
                ('galeria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.gallery')),
                ('imagem_previa', models.ForeignKey(blank=True, help_text='Imagem prévia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.photo')),
            ],
        ),
        migrations.CreateModel(
            name='PostAnuncio',
            fields=[
                ('id_anuncio', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('texto_anuncio', models.TextField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriaanuncio')),
                ('galeria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.gallery')),
                ('imagem_previa', models.ForeignKey(blank=True, help_text='Imagem prévia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.photo')),
            ],
        ),
    ]
